### ISSUE TITLE
"kafka-client-relation-broken" hook fails when removing kafka-test-app

### ISSUE THREAD

**Issue by Basdbruijne** [canonical/kafka-operator#104]
When deploying kafka, I deployed the kafka-test-app and then removed it before it was completely set up. This put the kafka charm in an error state:

```
kafka/0*                      error     idle        0        10.246.167.102           hook failed: "kafka-client-relation-broken"
  ntp/0*                      active    idle                 10.246.167.102  123/udp  chrony: Ready
kafka/1                       waiting   idle        1        10.246.166.233           Awaiting restart operation
  ntp/1                       active    idle                 10.246.166.233  123/udp  chrony: Ready
kafka/2                       waiting   idle        2        10.246.166.8             Awaiting restart operation
  ntp/2                       active    idle                 10.246.166.8    123/udp  chrony: Ready
tls-certificates-operator/0*  active    idle        3        10.246.166.140
zookeeper/0                   active    idle        4        10.246.164.162
zookeeper/1                   active    idle        5        10.246.164.244
zookeeper/2*                  active    idle        6        10.246.167.95
```

In the debug-log we see:
```
unit-kafka-0: 19:40:57 DEBUG unit.kafka/0.juju-log kafka-client:11: cmd failed - cmd= charmed-kafka.configs --bootstrap-server=10.246.166.233:9093,10.246.167.102:9093,10.246.166.8:9093 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties --alter --entity-type=users --entity-name=relation-11 --delete-config=SCRAM-SHA-512, stdout=, stderr=Error while executing config command with args '--bootstrap-server=10.246.166.233:9093,10.246.167.102:9093,10.246.166.8:9093 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties --alter --entity-type=users --entity-name=relation-11 --delete-config=SCRAM-SHA-512'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ResourceNotFoundException: Attempt to delete a user credential that does not exist
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at kafka.admin.ConfigCommand$.alterUserScramCredentialConfigs(ConfigCommand.scala:464)
        at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:427)
        at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:326)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:97)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.ResourceNotFoundException: Attempt to delete a user credential that does not exist

unit-kafka-0: 19:40:57 ERROR unit.kafka/0.juju-log kafka-client:11: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kafka-0/charm/./src/charm.py", line 509, in <module>
    main(KafkaCharm)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 354, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 830, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 919, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/provider.py", line 141, in _on_relation_broken
    self.kafka_auth.delete_user(username=username)
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/auth.py", line 199, in delete_user
    KafkaSnap.run_bin_command(bin_keyword="configs", bin_args=command)
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/snap.py", line 180, in run_bin_command
    raise e
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/snap.py", line 173, in run_bin_command
    output = subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command ' charmed-kafka.configs --bootstrap-server=10.246.166.233:9093,10.246.167.102:9093,10.246.166.8:9093 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties --alter --entity-type=users --entity-name=relation-11 --delete-config=SCRAM-SHA-512' returned non-zero exit status 1.
```

It looks like the charm is too eager to remove the credentials for the application that never finished setting up. When I kafka-test-app settle before removing it, the kafka charm does handle the departure properly. This only happens when the test app is removed prematurely.

**Comment by deusebio** [comment]
closed by #114
