### ISSUE TITLE
Kafka-test-app and kafka relation slow

### ISSUE THREAD

**Issue by deusebio** [canonical/kafka-operator#131]
When creating a relation between the [kafka-test-app](https://github.com/canonical/kafka-test-app) and kafka, the process is very slow when multi-broker deployments are considered. The logs show some exceptions which may be the source of the problem. Eventually the relation gets created properly, but this takes ~10 minutes which seems excessive. 

## Steps to reproduce

1. `juju model-config logging-config="<root>=DEBUG`
2. `juju deploy ch:kafka -n 3 --channel 3/edge`
3. `juju deploy ch:zookeeper -n 3 --channel 3/edge`
4. `juju relate kafka zookeeper`
(wait for kafka and zookeeper to settle down)
5. `juju deploy kafka-test-app producer --channel edge -n1 --config role=producer --config topic_name=test-topic --config num_messages=100000`
6. `juju relate producer kafka`

## Versions

Operating system: Ubuntu 22.04.3 LTS

Juju CLI: 3.1.5-genericlinux-amd64

Juju agent:  3.1.5 

juju status:

```
Model  Controller  Cloud/Region         Version  SLA          Timestamp
apps   overlord    localhost/localhost  3.1.5    unsupported  14:42:10Z

App        Version  Status  Scale  Charm           Channel  Rev  Exposed  Message
kafka               active      3  kafka           3/edge   134  no
producer            active      1  kafka-test-app  edge       6  no       Please relate with Kafka or use the action to run the application without the relation.
zookeeper           active      3  zookeeper       3/edge   106  no

Unit          Workload  Agent      Machine  Public address  Ports  Message
kafka/0*      active    executing  0        10.21.168.168
kafka/1       active    idle       1        10.21.168.72           machine system settings are not optimal - see logs for info
kafka/2       active    idle       2        10.21.168.162          machine system settings are not optimal - see logs for info
producer/0*   active    idle       6        10.21.168.172          Please relate with Kafka or use the action to run the application without the relation.
zookeeper/0   active    idle       3        10.21.168.161
zookeeper/1*  active    idle       4        10.21.168.81
zookeeper/2   active    idle       5        10.21.168.204

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.21.168.168  juju-8cc559-0  ubuntu@22.04      Running
1        started  10.21.168.72   juju-8cc559-1  ubuntu@22.04      Running
2        started  10.21.168.162  juju-8cc559-2  ubuntu@22.04      Running
3        started  10.21.168.161  juju-8cc559-3  ubuntu@22.04      Running
4        started  10.21.168.81   juju-8cc559-4  ubuntu@22.04      Running
5        started  10.21.168.204  juju-8cc559-5  ubuntu@22.04      Running
6        started  10.21.168.172  juju-8cc559-6  ubuntu@22.04      Running
``` 

LXD: 5.17

## Log output

Juju debug log: 

```
unit-kafka-0: 14:33:39 DEBUG unit.kafka/0.juju-log kafka-client:9: cmd failed - cmd= charmed-kafka.configs --alter --entity-type=users --entity-name=relation-9 --add-config=SCRAM-SHA-512=[password=6t5aQusn98gJ830dnhNKeRURd6fr0Ioc] --bootstrap-server=10.21.168.72:9092,10.21.168.162:9092,10.21.168.168:9092 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties, stdout=, stderr=[2023-08-30 14:32:39,248] WARN [AdminClient clientId=adminclient-1] Connection to node -2 (juju-8cc559-2.lxd/10.21.168.162:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,256] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (juju-8cc559-1.lxd/10.21.168.72:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,272] WARN [AdminClient clientId=adminclient-1] Connection to node -3 (juju-8cc559-0.lxd/10.21.168.168:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,375] WARN [AdminClient clientId=adminclient-1] Connection to node -2 (juju-8cc559-2.lxd/10.21.168.162:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,378] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (juju-8cc559-1.lxd/10.21.168.72:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,380] WARN [AdminClient clientId=adminclient-1] Connection to node -3 (juju-8cc559-0.lxd/10.21.168.168:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,491] WARN [AdminClient clientId=adminclient-1] Connection to node -2 (juju-8cc559-2.lxd/10.21.168.162:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,492] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (juju-8cc559-1.lxd/10.21.168.72:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,494] WARN [AdminClient clientId=adminclient-1] Connection to node -3 (juju-8cc559-0.lxd/10.21.168.168:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,697] WARN [AdminClient clientId=adminclient-1] Connection to node -2 (juju-8cc559-2.lxd/10.21.168.162:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,699] WARN [AdminClient clientId=adminclient-1] Connection to node -3 (juju-8cc559-0.lxd/10.21.168.168:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2023-08-30 14:32:39,802] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (juju-8cc559-1.lxd/10.21.168.72:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
Error while executing config command with args '--alter --entity-type=users --entity-name=relation-9 --add-config=SCRAM-SHA-512=[password=6t5aQusn98gJ830dnhNKeRURd6fr0Ioc] --bootstrap-server=10.21.168.72:9092,10.21.168.162:9092,10.21.168.168:9092 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at kafka.admin.ConfigCommand$.alterUserScramCredentialConfigs(ConfigCommand.scala:464)
        at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:427)
        at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:326)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:97)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials
```

This message appears quite a few times, sometimes somewhat shorter:

```
unit-kafka-0: 14:43:05 DEBUG unit.kafka/0.juju-log restart:2: cmd failed - cmd= charmed-kafka.configs --alter --entity-type=users --entity-name=relation-9 --add-config=SCRAM-SHA-512=[password=kpNjOzYN013Wq9UYxckb0RaFUg0rggYv] --bootstrap-server=10.21.168.72:9092,10.21.168.162:9092,10.21.168.168:9092 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties, stdout=, stderr=Error while executing config command with args '--alter --entity-type=users --entity-name=relation-9 --add-config=SCRAM-SHA-512=[password=kpNjOzYN013Wq9UYxckb0RaFUg0rggYv] --bootstrap-server=10.21.168.72:9092,10.21.168.162:9092,10.21.168.168:9092 --command-config=/var/snap/charmed-kafka/current/etc/kafka/client.properties'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
        at kafka.admin.ConfigCommand$.alterUserScramCredentialConfigs(ConfigCommand.scala:464)
        at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:427)
        at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:326)
        at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:97)
        at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: alterUserScramCredentials

```

**Comment by deusebio** [comment]
We have conducted an investigation and this is due to the fact that the Kafka cluster is "Secured by default" when deployed, meaning that external ports are closed, and they are opened only upon creating the relevant client relations. Therefore the long startup time for adding the first relation is due to the fact that all brokers have to restart, opening the port, before ACLs can be set using the kafka bin commands. 

This creates a bit of lagging and a bit longer startup time. However, after the ports are open (e.g. after the first client application is related), successive client relations are indeed very quick. 

Thus, this is not thought to be an issue, as one of the best-practices we recommend for deployments is to always deploy a data-integrator with admin credentials to perform admin operations on the Kafka cluster. When this is done, client application relation should be rather quick and smooth.
