### ISSUE TITLE
Uncaught exception when removing the certificates relation

### ISSUE THREAD

**Issue by sed-i** [canonical/kafka-operator#66]
## Issue
I added a dummy certificates relation to a charm and related to kafka. After removing the app, kafka goes into error state.

```
unit-kafka-0: 12:24:39.356 DEBUG unit.kafka/0.juju-log certificates:7: Re-emitting <RelationChangedEvent via KafkaCharm/on/cluster_relation_changed[163]>.
unit-kafka-0: 12:24:39.363 ERROR unit.kafka/0.juju-log certificates:7: TLS must be enabled for Zookeeper and Kafka
unit-kafka-0: 12:24:39.422 DEBUG unit.kafka/0.juju-log certificates:7: Deferring <RelationChangedEvent via KafkaCharm/on/cluster_relation_changed[163]>.
unit-kafka-0: 12:24:39.430 DEBUG unit.kafka/0.juju-log certificates:7: Emitting Juju event certificates_relation_broken.
unit-kafka-0: 12:24:39.452 ERROR unit.kafka/0.juju-log certificates:7: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-kafka-0/charm/./src/charm.py", line 476, in <module>
    main(KafkaCharm)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/main.py", line 435, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 355, in emit
    framework._emit(event)  # noqa
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 824, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-kafka-0/charm/venv/ops/framework.py", line 899, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/tls.py", line 85, in _tls_relation_broken
    self.remove_stores()
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/tls.py", line 310, in remove_stores
    raise e
  File "/var/lib/juju/agents/unit-kafka-0/charm/src/tls.py", line 301, in remove_stores
    subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'rm -r *.pem *.key *.p12 *.jks' returned non-zero exit status 1.
unit-kafka-0: 12:24:39.685 ERROR juju.worker.uniter.operation hook "certificates-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```

## Possible solution
Should the `rm` be called with `-f`?

## Additional context
To be fair, the charm with the dummy "certificates" relation does not use the lib or anything else - reldata is always blank on that side.

**Comment by marcoppenheimer** [comment]
@sed-i - Thanks for raising, I don't think we handled the case of having empty relation data (and by extension, not adding the files in the first place). Have addressed in open PR. Closing.
