### ISSUE TITLE
Flaky integration tests

### ISSUE THREAD

**Issue by sed-i** [canonical/kafka-operator#73]
While iterating on #69, I noticed some issues with the existing itests:

1. None of the tests pass with juju 3. Haven't tested, but at the very least would need to pin python-libjuju: `juju ~= 3.0.0` so it works with both juju 2.9 and 3.
2. The following tests *occasionally* fail.

### test_provider.py::test_deploy_charms_relate_active
`wait_for_idle` timeout elapses while still in `maitenance`:

```
Traceback (most recent call last):
  File "/home/runner/work/kafka-operator/kafka-operator/tests/integration/test_provider.py", line 47, in test_deploy_charms_relate_active
    await ops_test.model.wait_for_idle(apps=[APP_NAME, DUMMY_NAME_1, ZK])
  File "/home/runner/work/kafka-operator/kafka-operator/.tox/integration-provider/lib/python3.10/site-packages/juju/model.py", line 2713, in wait_for_idle
    raise jasyncio.TimeoutError("Timed out waiting for model:\n" + busy)
asyncio.exceptions.TimeoutError: Timed out waiting for model:
zookeeper/2 [executing] maintenance: installing ZooKeeper Snap
```

### test_scaling.py::test_kafka_simple_scale_up
```
Traceback (most recent call last):
  File "/home/runner/work/kafka-operator/kafka-operator/tests/integration/test_scaling.py", line 38, in test_kafka_simple_scale_up
    assert ops_test.model.applications[APP_NAME].status == "active"
AssertionError: assert 'waiting' == 'active'
  - active
  + waiting
```

```
Traceback (most recent call last):

File "/home/runner/work/kafka-operator/kafka-operator/tests/integration/test_scaling.py", line 70, in test_kafka_simple_scale_down

assert f"{chroot}/brokers/ids/2" in active_brokers

AssertionError: assert '/kafka/brokers/ids/2' in {'/kafka/brokers/ids/', '/kafka/brokers/ids/0'}
```

### test_tls.py::test_deploy_tls
```
Traceback (most recent call last):
  File "/home/runner/work/kafka-operator/kafka-operator/tests/integration/test_tls.py", line 44, in test_deploy_tls
    await ops_test.model.wait_for_idle(apps=[APP_NAME, ZK_NAME, TLS_NAME], timeout=1000)
  File "/home/runner/work/kafka-operator/kafka-operator/.tox/integration-tls/lib/python3.10/site-packages/juju/model.py", line 2713, in wait_for_idle
    raise jasyncio.TimeoutError("Timed out waiting for model:\n" + busy)
asyncio.exceptions.TimeoutError: Timed out waiting for model:
kafka/0 [executing] maintenance: installing charm software
```

**Comment by marcoppenheimer** [comment]
@sed-i - Yeah, a lot of those tests are due to the CI runners being too small. We're maxing out CPU on build steps, but there's been a few changes to help with that so hopefully it gets more stable. But as you know, re-running the failing tests usually helps resolve once the runner has more CPU available. 

With the `AssertionError: assert '/kafka/brokers/ids/2' in {'/kafka/brokers/ids/', '/kafka/brokers/ids/0'}` failure however, that looks like a more reasonable, 'actual' failure. It's likely however that it's related to the same issues as with the other failing tests (which is a bug in Juju where they only recognize 'Active' and 'Blocked' status, not 'Waiting').

I believe these are mostly addressed in https://github.com/canonical/kafka-operator/pull/74, so will close this issue. Please reopen if it persists after merge
